version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando la fase de pre-construcción...
      - wget https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
      - tar -xvf tmas-cli_Linux_x86_64.tar.gz
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Construyendo la imagen Docker...
      - docker build -t ecs-demo .
      - docker tag ecs-demo:latest 199694721883.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
      - ./tmas-cli_Linux_x86_64.tar/tmas scan docker-archive:ecs-demo:latest > result.json
  post_build:
    commands:
      - echo Empujando la imagen a ECR...
      - docker push 199694721883.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest
      - echo Creando archivo imagedefinitions.json...
      - printf '[{"name":"ecs-demo","imageUri":"%s"}]' 199694721883.dkr.ecr.us-east-1.amazonaws.com/ecs-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
